version: '3.3'

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=supersecretpassw
      - POSTGRES_USER=db_manager
      - POSTGRES_DB=foodgram
    volumes:
      - postgres_data:/var/lib/postgresql/data


  django:
    build: ../backend/
    env_file: .env
    volumes:
      - static_volume:/backend/collected_static
      - media_volume:/backend/media
    depends_on:
      - db

  frontend:
    build: ../frontend/
    command: cp -r /app/build/. /static/
    env_file: .env
    volumes:
      - static_volume:/static

  nginx:
    build: ../nginx/
    env_file: .env
    ports:
      - "8000:80"
    volumes:
      - static_volume:/static/
      - media_volume:/media/
    depends_on:
      - django
