# Generated by Django 5.0.4 on 2024-05-05 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ricepe', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-pub_date'], 'verbose_name': 'рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
