# Generated by Django 5.0.4 on 2024-04-15 12:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('measurement_unit', models.CharField(max_length=12, verbose_name='Единица измерения')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Имя')),
                ('color', models.CharField(max_length=16, unique=True)),
                ('slug', models.SlugField(max_length=25, unique=True, verbose_name='Слаг')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient_Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='колличество')),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='ricept.ingredient', verbose_name='Ингредиент')),
            ],
            options={
                'verbose_name': 'Связь жанра и произведения',
                'verbose_name_plural': 'Связи жанров и произведений',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cooking_time', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='ололо')], verbose_name='Время готовки')),
                ('image', models.ImageField(default=None, null=True, upload_to='recipes/images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('ingredients', models.ManyToManyField(through='ricept.Ingredient_Recipe', to='ricept.ingredient', verbose_name='Ингредиент')),
                ('tags', models.ManyToManyField(to='ricept.tag', verbose_name='Ингредиент')),
            ],
            options={
                'verbose_name': 'рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.AddField(
            model_name='ingredient_recipe',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='ricept.recipe', verbose_name='Рецепт'),
        ),
    ]
